name: build
# Triggered by changes in code-specific or job-specific files

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/*.yml'
      - '.pylintrc'
      - '.pre-commit-config.yaml'
      - '.pydocstyle'
      - '.relint.yml'
      - '.yamllint'
      - 'tox.ini'
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Generic pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: pip install pre-commit
      - run: SKIP=pylint pre-commit run --all-files

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: pip install pre-commit
      - run: pre-commit run pylint --all-files

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.5, 3.6, 3.7, 3.8, 3.9.0-rc.1, pypy3]

    name: ${{ matrix.os }}/tests_${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: pip install tox coverage

      - name: Run ${{ matrix.python }} tox job
        run: tox -e py
        env:
          TOX_JOB: ${{ matrix.python }}

      - run: coverage combine
      - run: coverage report
      - run: coverage xml -i

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-py${{ matrix.python }}
